macros/tests/tx_gaps.sql
tests/ethereum/silver__transactions__tx-gap.sql

adding a test to compare txs per block in a given model vs. the blocks model

add tx gap bespoke test

---

models/bronze/bronze__blocks.sql
models/bronze/bronze__transactions.sql
models/silver/silver__blocks.sql
models/silver/silver__blocks.yml
models/silver/silver__contracts_extended.yml
models/silver/silver__logs.sql
models/silver/silver__logs.yml
models/silver/silver__transactions.sql
models/silver/silver__transactions.yml

adding logic to handle extra txs (likely uncles) and formatting updates. Also fixed issue with decimals on tx fees.

fix uncles + tx fee

---

models/silver/traces/silver__traces.sql

backfill is stuck on blocks with 0 txs right now

fix 0 tx blocks

---

models/gold/core__ez_nft_mints.sql
models/gold/core__ez_nft_mints.yml

- this view is slow AF in velocity
- changing to incremental table logic

change to table logic

---

models/silver/silver__blocks.yml

- filter out blocks being backfilled

update gap test

---

dbt_project.yml
macros/sp_create_cross_db_share_clones.sql
models/gold/secure_views/core__sv_dim_dex_liquidity_pools.sql
models/gold/secure_views/core__sv_dim_labels.sql
models/gold/secure_views/core__sv_fact_hourly_token_prices.sql
models/sources.yml

- clone tables needed for data share as cross db views are not shareable

clone cross db sources that need to be in data shares

---

dbt_project.yml
macros/create_udfs.sql
macros/create_udfs_public.sql
macros/js_hextoint.sql
macros/python/udfs.sql
macros/udf_load_nft_metadata.sql

- create python udf
- clean up create_udfs.sql
- clean up macro names for creating udfs

Create udf to convert hext to int

---

macros/sp_create_prod_clone.sql
models/sources.yml

- dev external tables should look at dev stage now
- refresh should set proper perms for dev stage

An 1569/fix external tables issue

---

models/gold/core__ez_eth_transfers.sql

exclude failed traces, like this tx: https://ethtx.info/mainnet/0x1a19a53f17e71df604f39b55cffac4e8c04c799035e81d273e34cc787253497d/

exclude failures

---

models/bronze/bronze__blocks.sql
models/bronze/bronze__transactions.sql
models/gold/core__ez_eth_transfers.sql
models/gold/core__ez_nft_transfers.sql
models/gold/core__ez_token_transfers.sql
models/gold/core__fact_blocks.sql
models/gold/core__fact_event_logs.sql
models/gold/core__fact_token_transfers.sql
models/gold/core__fact_traces.sql
models/gold/core__fact_transactions.sql
models/silver/silver__blocks.sql
models/silver/silver__eth_transfers.sql
models/silver/silver__logs.sql
models/silver/silver__nft_transfers.sql
models/silver/silver__transactions.sql
models/silver/silver__transfers.sql
models/silver/traces/silver__traces.sql
models/silver/traces/silver__traces_new.sql

- swap incremental logic to `_inserted_timestamp`
- build a new table for traces, will hot swap once backfill completes in ~12 hours

An 1424/inserted timestamp

---

models/silver/dex/silver_dex__v2_swaps.sql

improving price_USD so that It shows for one side, even if we dont have data for the other side

allowing one side price data to show

---

macros/sp_create_prod_clone.sql

- ensure bronze is owned by role AWS_LAMBDA_ETHEREUM_API

Clone SP Updated for bronze streamline

---

models/silver/streamline/streamline__eth_balances_history.sql
models/silver/streamline/streamline__token_balances_history.sql

Streamline Performance Enhancment

---

models/silver/streamline/streamline__complete_eth_balances.sql

- add default date when no max inserted date is present

Fix Max Inserted Timestamp NULL

---

models/silver/streamline/streamline__eth_balances_history.sql
models/silver/streamline/streamline__token_balances_history.sql

- use macros to create partitioned views to improve query performance

Streamline History Model Improvements

---

models/silver/nft/silver_nft__opensea_sales.yml
models/silver/nft/silver_nft__seaport_sales.sql

adds a new fee contract to the opensea seaport model

add new fee contract to seaport model

---

models/silver/optimism/silver__optimism_state_hashes.sql
models/silver/optimism/silver__optimism_state_hashes.yml
models/silver/optimism/silver__optimism_submission_hashes.sql
models/silver/optimism/silver__optimism_submission_hashes.yml

create optimism silver tables + tests

---

macros/sp_create_prod_clone.sql

- grant future select on bronze to internal_dev

grant future select on bronze to internal_dev

---

data/silver__chainlink_feeds_seed.csv

add seed file

---

models/gold/aave/aave__ez_market_stats.yml
models/gold/aave/silver__aave_liquidity_mining.yml
models/gold/aave/silver__aave_oracle_prices.yml
models/silver/balances/silver__daily_eth_balances.yml
models/silver/balances/silver__daily_token_balances.yml
models/silver/balances/silver__eth_balances.yml
models/silver/balances/silver__token_balances.yml
models/silver/silver__blocks.yml
models/silver/silver__transactions.yml
models/silver/traces/silver__traces.yml
tests/ethereum/test_silver__transactions_tx_gaps.sql

AAVE 
- these errors are from model runner - turning these off till built off streamline
- these are not exposed in prod 
Balances Models
- more (bigger) changes are coming for these models in a different PR
- these are not exposed in prod
Blocks model
- missing blocks ticketed with [PL-116](https://team-1612274056224.atlassian.net/browse/PL-116)
TX Model
- two weird blocks with mismatched tx hash / block number [PL-123](https://team-1612274056224.atlassian.net/browse/PL-123)
Traces 
- missing traces on some blocks [PL-92](https://team-1612274056224.atlassian.net/browse/PL-92)

An 1881 turn off know failures

---

models/silver/balances/silver__eth_balance_diffs.sql
models/silver/balances/silver__token_balance_diffs.sql

correctly handle previous value

update incremental logic

---

macros/sp_create_prod_clone.sql
macros/streamline/streamline_udfs.sql
macros/utils.sql

- only update udfs if they don't exist
- use if/else in clone sproc
- add limit 1 to streamline post hook queries

Streamline Permissions Post-Hook Enhancements

---

models/silver/nft/silver_nft__cryptopunk_sales.sql
models/silver/silver__nft_transfers.sql

uses topics and data for punks sales

punks update

---

models/silver/traces/silver__traces.sql

turn up traces for genesis backfill

speed traces

---

models/silver/streamline/streamline__complete_reads.sql

tweaks incremental load for better usage of partitions

incremental improvements

---

models/silver/silver__blocks.yml

add severity to eth block gap test

tweak block test

---

models/silver/nft/silver_nft__seaport_sales.sql
models/silver/nft/silver_nft__sudoswap_sales.sql

- rebuilds the sudoswap model to correctly handle fees + more complicated tx types
- adds a new fee contract to the OS model
- both models need FRs

An 1959/sudo fee

---

models/silver/nft/silver_nft__opensea_sales.sql

creator fee change

---

models/silver/silver__contracts.sql

Changes made upon token with the DAI symbol. For tokens with symbol DAI are labeled the name column instead.

tweak_DAI_label

---

models/silver/silver__contracts.sql

Reverts FlipsideCrypto/ethereum-models#187

Revert "tweak_DAI_label"

---

models/silver/streamline/streamline__eth_balances_by_date.sql
models/silver/streamline/streamline__token_balances_by_date.sql

Rever to previous version of balances models

Revert Last PR

---

models/compound/silver/silver__comp_market_stats.sql

- will now only include comp tokens

only include comp pools

---

models/silver/silver__token_meta_reads.sql

this will only include the uni v3 tokens in the contracts model, larger contracts PR is forthcoming

only uni token model

---

models/silver/streamline/curated/streamline__curve_pool_reads.sql

adding more contract deployers to read

more curve reads

---

models/silver/silver__nft_transfers.sql
models/silver/silver__nft_transfers.yml

-  The nft_transfer_table has updated with new changes to fix the bug from discord ticket [ AN -1961]

Nft transfer updated table

---

data/silver__chainlink_feeds_seed.csv
models/silver/streamline/curated/streamline__chainlink_prices.sql
models/silver/streamline/streamline__contract_reads.sql

-adds chainlink prices to reads lambda

chainlink reads

---

models/compound/gold/compound__ez_liquidations.yml
models/silver/nft/silver_nft__rarible_sales.yml

- building new rarible model
- backing up liquidation recency test

test tweaks

---

README.md
macros/create_udfs.sql
macros/streamline/get_base_table_udtf.sql
macros/streamline/streamline_udfs.sql
models/silver/streamline/streamline__beacon_blocks.sql
models/silver/streamline/streamline__beacon_blocks_history.sql
models/silver/streamline/streamline__beacon_blocks_realtime.sql
models/silver/streamline/streamline__blocks.sql
models/silver/streamline/streamline__blocks_history.sql
models/silver/streamline/streamline__blocks_realtime.sql
models/silver/streamline/streamline__complete_beacon_blocks.sql
models/silver/streamline/streamline__transactions_history.sql
models/silver/streamline/streamline__transactions_realtime.sql

- added post hooks to history and realtime models
- added instructions in readme for using variables
- updated naming conventions

updated blocks, transactions, and beacon blocks models

---

macros/create_udfs.sql
macros/streamline/streamline_udfs.sql

- added Macros for: call_node, call_api, call_read_batching

Added DBT UDFs

---

.user.yml
dbt_project.yml
macros/create_sps.sql
macros/create_udfs.sql
macros/sp_create_cross_db_share_clones.sql
macros/sp_create_load_nft_metadata.sql

Added project level variable and associated IF statements to on-run-start macros to default UDF/SP updates to False,  preventing macros from being created on every dbt run, unless required (e.g. set UPDATE_UDFS_AND_SPS: True)

AN-2390/update-vars-udf-sps

---

macros/streamline/streamline_udfs.sql

Reverts FlipsideCrypto/ethereum-models#267

Revert "Create or replace UDF"

---

README.md

- updated README to include info on project lvl vars (update udfs and sps)
- [Jira Ticket](https://team-1612274056224.atlassian.net/browse/AN-2416)

AN-2416/readme-vars-eth

---

models/silver/prices/silver__token_prices_coin_gecko_hourly.yml
models/silver/prices/silver__token_prices_coin_market_cap_hourly.yml

- Changed date interval in silver hourly token price tests from 2 days to 1 day
- [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2430)

AN-2430/recency-test-adj

---

.user.yml
models/gold/core__fact_hourly_token_prices.sql

- Updated core hourly prices model with reference to new token price models that source coingecko and coinmarketcap prices
- [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2385?atlOrigin=eyJpIjoiNTAxNGFiNzkwOTE2NDc4NDlkMWI5ZDcwNjE5MGNlNmQiLCJwIjoiaiJ9)

AN-2385/core-hrly-prices

---

models/silver/dex/silver_dex__synthetix_swaps.sql
models/silver/dex/silver_dex__synthetix_swaps.yml

1. Reviewed the synthetix swaps model to verify accuracy & simplified the model for efficiency / readability
2. Requires full refresh
3. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2512?atlOrigin=eyJpIjoiOWI1MTVhNzBmZGFmNDc1MjlkM2Q0NmFjZDM1NWViYzEiLCJwIjoiaiJ9)

AN-2512/snx-swaps-review

---

models/chainlink/gold/chainlink__dim_feeds.sql
models/chainlink/gold/chainlink__dim_feeds.yml
models/chainlink/gold/chainlink__ez_feeds.sql
models/chainlink/gold/chainlink__ez_feeds.yml
models/chainlink/gold/chainlink__fact_feeds.sql
models/chainlink/gold/chainlink__fact_feeds.yml
models/chainlink/silver/silver__chainlink_feeds.sql
models/chainlink/silver/silver__chainlink_feeds.yml

adds a schema for chainlink oracle feeds

chainlink models

---

data/silver__chainlink_feeds_seed.csv

need to run a dbt seed in prod on this + a FR of `models/silver/streamline/curated/streamline__chainlink_prices.sql` to queue reads

add nft floor feeds

---

macros/tests/tx_block_count.sql
models/silver/silver__logs.sql
models/silver/silver__logs.yml
models/silver/traces/silver__traces.sql
tests/ethereum/test_silver__logs_tx_gaps.sql

1. Added tx_gaps test to `silver_logs`
2. Changed unique key to tx_hash in `silver_logs` and `silver_traces`
3. Requested three affected blocks be replayed by chainwalkers
4. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2572)

AN-2572/eth-tx-hash-fix

---

macros/create_udfs.sql
macros/python/transform_logs.sql
models/gold/beta/beta__fact_decoded_logs.sql
models/gold/beta/beta__fact_decoded_logs.yml
models/silver/silver__decoded_logs.sql
models/silver/silver__decoded_logs.yml

adds beta table for logs decoding - this only includes blocks 14m-16m and will be excluded from incremental runs.

An 2605/decoded data

---

macros/tests/avg_row_count.sql
macros/tests/row_count.sql
models/bronze/bronze__successful_reads.yml
models/silver/balances/silver__eth_balances.yml
models/silver/balances/silver__token_balances.yml

custom tests for looking at row count anomalies in streamline model rows

macros and tests

---

.github/workflows/dbt_run_adhoc.yml
.github/workflows/dbt_run_dev_refresh.yml
.github/workflows/dbt_run_incremental_non_real_time.yml
.github/workflows/dbt_run_incremental_real_time.yml
.github/workflows/dbt_run_streamline_beacon_blocks.yml
.github/workflows/dbt_run_streamline_blocks.yml
.github/workflows/dbt_run_streamline_contract_abis.yml
.github/workflows/dbt_run_streamline_decoder.yml
.github/workflows/dbt_run_streamline_eth_token_balances.yml
.github/workflows/dbt_run_streamline_reads.yml
.github/workflows/dbt_run_streamline_transactions.yml
.github/workflows/dbt_test.yml
profiles.yml

1. Added github workflows folder
2. Added 11 new jobs (incremental, adhoc, tests, dev_db_refresh, incremental real time and non-real time, strreamline (beacon blocks, blocks, contract abis, eth token bal, reads and txns) based on existing dbt cloud jobs, matching scheduled run times and dbt commands
3. Included standardized naming conventions
4. Modified profiles.yml accordingly

add-github-actions-ethereum

---

.github/workflows/dbt_run_streamline_decoder.yml
models/doc_descriptions/general/__overview__.md
models/gold/beta/beta__fact_decoded_logs.yml
models/gold/core__dim_contract_abis.sql
models/gold/core__dim_contract_abis.yml
models/gold/core__ez_decoded_event_logs.sql
models/gold/core__ez_decoded_event_logs.yml
models/gold/core__ez_decoded_logs.sql
models/gold/core__fact_decoded_event_logs.sql
models/gold/core__fact_decoded_event_logs.yml
models/gold/core__fact_decoded_logs.sql
models/silver/abis/silver__user_verified_abis.sql
models/sources.yml

- adds three new tables to gold, `dim_contract_abis`, `fact_decoded_event_logs` and `ez_decoded_event_logs`
- moves user abi source from ethereum to crosschain 
- updates docs

An 2712/gold decoded tables

---

models/silver/silver__contracts.sql
models/silver/silver__token_meta_reads.sql
models/silver/silver__token_meta_reads.yml

- add reads from node UDF to get new, non-uni contracts

improve contracts

---

models/silver/silver__nft_transfers.sql

1. Added `project_name` from new `silver_contracts` model to fill gaps
2. All models dependent on `silver_nft_transfers` requires a FR

AN-2729/null-nft-names

---

macros/sp_create_prod_clone.sql

1. Updated `sp_create_prod_clone` with new format/process 
2. Added var to fix issue with snowflake tagging on dev
3. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2728?atlOrigin=eyJpIjoiYjNiODU0ODFmMDlkNDIxMGI2ZmQ4NTI2MjE5MjkzMjciLCJwIjoiaiJ9)

AN-2728/dev-tag-fix-ethereum

---

models/silver/silver__transfers.sql

- removes usage of event name / event inputs
- also removes some transfers that shouldnt be in this table 
- fixes AN-2490 missing transfers

rework transfers without event inputs / name

---

models/doc_descriptions/general/__overview__.md

dbt docs overview update

---

models/doc_descriptions/general/__overview__.md

removes advanced markdown for now, ticket opened with dbt for this [issue](https://github.com/dbt-labs/dbt-docs/issues/368)

Dbt docs md

---

.github/workflows/dbt_docs_update.yml
.github/workflows/dbt_run_adhoc.yml
.github/workflows/dbt_run_dev_refresh.yml
.github/workflows/dbt_run_incremental_non_real_time.yml
.github/workflows/dbt_run_incremental_real_time.yml
.github/workflows/dbt_run_streamline_beacon_blocks.yml
.github/workflows/dbt_run_streamline_blocks.yml
.github/workflows/dbt_run_streamline_contract_abis.yml
.github/workflows/dbt_run_streamline_decoder.yml
.github/workflows/dbt_run_streamline_decoder_history.yml
.github/workflows/dbt_run_streamline_eth_token_balances.yml
.github/workflows/dbt_run_streamline_reads.yml
.github/workflows/dbt_run_streamline_transactions.yml
.github/workflows/dbt_test.yml

1. Modified workflows to reference `environment variables` instead of `secrets` for non-sensitive variables
2. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2756)

AN-2756/env-var-update

---

models/Sushi/sushi__ez_borrowing.yml
models/Sushi/sushi__ez_lending.yml

1. Added `Deprecating soon` to core sushi model descriptions
2. Removed tests from applicable yml files

AN-2785/sushi-tests-eth

---

models/doc_descriptions/general/deprecation.md
models/gold/core__fact_event_logs.yml
models/gold/core__fact_transactions.yml

- adds deprecation notice to impacted columns of decoding transition

add deprecation notice

---

analysis/udf_transform_test.py
dbt_project.yml
models/silver/streamline/streamline__contract_abis_realtime.sql
models/silver/streamline/streamline__reads_realtime.sql

- remove history models from realtime models

Streamline realtime view optimizations

---

.github/workflows/dbt_run_streamline_contract_abis.yml
.github/workflows/dbt_run_streamline_eth_token_balances.yml
.github/workflows/dbt_run_streamline_reads.yml

- offset schedule for models that use eth_call

AN-2897/offset-streamline-schedule-realtime

---

models/silver/streamline/streamline__transactions_history.sql

Backfill Missing Token Balances 16M

---

macros/tests/recent_dupes.sql
models/bronze/core/bronze__streamline_traces.sql
models/bronze/core/bronze__streamline_traces.yml
models/silver/core/_tx_status.sql
models/silver/core/silver__streamline_traces.sql
models/silver/core/silver__streamline_traces.yml

- adds a macro to test recent dupes
- adds bronze and silver layer for eth traces from streamline, with tests

new streamline traces

---

models/aave/gold/aave__ez_proposals.sql
models/aave/gold/aave__ez_proposals.yml
models/aave/silver/silver__aave_created_proposals.sql
models/aave/silver/silver__aave_executed_proposals.sql
models/aave/silver/silver__aave_queued_proposals.sql
models/silver/streamline/_block_ranges.sql

- builds underlying tables for proposal actions without old decoding
- adds helpful columns to gold and makes it a view

An 2893/aave pivot

---

.github/workflows/dbt_run_incremental_nft_metadata.yml
models/bronze/api_udf/nft/bronze_api__nft_metadata_details_reads.sql
models/bronze/api_udf/nft/bronze_api__nft_metadata_pages_reads.sql
models/silver/api_udf/silver__nft_metadata_reads.sql

- lowers limit 
- increases frequency

fix bug and increase refresh

---

.github/workflows/dbt_run_incremental_non_real_time.yml
.github/workflows/dbt_run_streamline_decoder.yml
models/bronze/bronze__successful_reads.yml
models/gold/core__ez_decoded_event_logs.sql
models/gold/core__fact_decoded_event_logs.sql
models/silver/silver__decoded_logs.sql
models/silver/silver__decoded_logs_full.sql
models/silver/silver__decoded_logs_full.yml

- speeds up decoded logs 
- removes row count test on reads

remove row count test on reads

---

models/silver/nft/silver_nft__complete_nft_sales.sql
models/silver/nft/silver_nft__complete_nft_sales.yml
models/silver/nft/silver_nft__cryptopunk_sales.yml
models/silver/nft/silver_nft__looksrare_v2.yml
models/silver/nft/silver_nft__nftx_decoded_sales.yml
models/silver/nft/silver_nft__rarible_decoded_sales.yml
models/silver/nft/silver_nft__seaport_1_4_sales.yml
models/silver/nft/silver_nft__seaport_1_5_sales.sql
models/silver/nft/silver_nft__seaport_1_5_sales.yml
models/silver/nft/silver_nft__sudoswap_sales.yml
models/silver/nft/silver_nft__x2y2_decoded_sales.yml

- Adding Seaport 1.5 into nft sales 
- changed logic to join in project_name / metadata 
- removed recency test for Seaport 1.4, added 2 day recency for other marketplaces except blur and seaport

[Not ready for merge] An 3119/seaport 1 5

---

models/gold/core__dim_labels.yml
models/silver/labels/silver__labels.yml

1. Moved tests to silver layer
2. FR required on silver__labels+ to resolve NULLs

AN-3202/labels-bugs

---

.github/workflows/dbt_run_incremental_beacon.yml
.github/workflows/dbt_run_streamline_beacon_chain_blocks.yml
.github/workflows/dbt_run_streamline_beacon_chain_history.yml
models/beacon_chain/bronze/blocks/bronze__beacon_blocks.sql
models/beacon_chain/bronze/blocks/bronze__fr_beacon_blocks.sql
models/beacon_chain/bronze/validators/bronze__beacon_validators.sql
models/beacon_chain/bronze/validators/bronze__fr_beacon_validators.sql
models/beacon_chain/silver/silver__beacon_blocks.sql
models/beacon_chain/silver/silver__beacon_validators.sql
models/silver/streamline/beacon/streamline__complete_beacon_blocks.sql
models/silver/streamline/beacon/streamline__complete_beacon_validators.sql

- adds a bronze layer to beacon models 
- backs off blocks requests to hourly 
- other misc workflow changes

add bronze layer

---

models/silver/nft/silver_nft__sudoswap_sales.sql

- revamped sudoswap nft sales model

sudoswap revamp

---

models/silver/dex/curve/silver_dex__curve_swaps.sql
models/silver/dex/curve/silver_dex__curve_swaps.yml
models/silver/dex/silver_dex__complete_dex_swaps.yml

Requires FR on curve_swaps and complete_dex_swaps

AN-3481/crv-token-addr

---

.github/workflows/dbt_run_temp.yml
models/silver/core/silver__confirmed_blocks.sql

confirmed blocks

---

models/silver/defi/liquid_staking/sharedstake/silver_lsd__sharedstake_v2_deposits.sql
models/silver/defi/liquid_staking/sharedstake/silver_lsd__sharedstake_v2_deposits.yml
models/silver/defi/liquid_staking/sharedstake/silver_lsd__sharedstake_v2_withdrawals.sql
models/silver/defi/liquid_staking/sharedstake/silver_lsd__sharedstake_v2_withdrawals.yml
models/silver/defi/liquid_staking/silver_lsd__complete_lsd_deposits.sql
models/silver/defi/liquid_staking/silver_lsd__complete_lsd_withdrawals.sql
models/silver/defi/liquid_staking/swell/silver_lsd__swell_deposits.sql

1. Added new event topic for Swell and new models for SharedStakeV2
2. Requires FR+

AN-3755/ss-swell-v2

---

.github/workflows/dbt_run_incremental_snapshot.yml
models/bronze/api_udf/snapshot/bronze_api__snapshot_proposals.sql
models/bronze/api_udf/snapshot/bronze_api__snapshot_votes.sql
models/bronze/api_udf/snapshot/bronze_api__snapshot_voting_strategy.sql
models/silver/governance/silver__snapshot.sql

- changes tags and adds new workflow

move snapshot

---

models/silver/defi/liquid_staking/sharedstake/silver_lsd__sharedstake_deposits.sql
models/silver/nft/silver_nft__looksrare_decoded_sales.sql
models/silver/nft/silver_nft__wyvern_decoded_sales.sql

- Updated incremental logic to help stale table models

stale-table-optimizations

---

models/bronze/api_udf/nft/bronze_api__nft_metadata_list.sql
models/bronze/api_udf/nft/bronze_api__nft_metadata_reads.sql

1. reduce batch size from 100 results to 50 results 
2. disable full refresh

Reduce batch size nft metadata

---

.github/workflows/dbt_run_incremental_temp.yml
models/silver/core/silver__traces2.sql
packages.yml

1. To use block/partition increment vars `dbt run -m models/silver/core/silver__traces2.sql --vars '{"max_block": 10000, "max_partition": 50000}`

New traces

---

models/bronze/api_udf/nft/bronze_api__nft_metadata_reads.sql
models/silver/nft/silver_nft__wyvern_decoded_sales.sql

reduce from range 5, 10 results each range to 6 range, 8 results each

Reduce metadata reads

---

models/bronze/api_udf/nft/bronze_api__nft_metadata_reads.sql

exclude rarible nft from metadata backfill for now, then run it exclusively filtering rarible nft only

exclude rarible nft

---

models/beacon_chain/gold/beacon_chain__ez_deposits.yml
models/beacon_chain/gold/beacon_chain__ez_withdrawals.yml
models/beacon_chain/gold/beacon_chain__fact_validator_balances.sql
models/beacon_chain/gold/beacon_chain__fact_validator_balances.yml
models/beacon_chain/gold/beacon_chain__fact_validators.sql
models/beacon_chain/gold/beacon_chain__fact_validators.yml

Requires `dbt run -m models/beacon_chain/gold/beacon_chain__fact_validator_balances.sql models/beacon_chain/gold/beacon_chain__fact_validators.sql --full-refresh`

beacon-val-column-names

---

models/gold/defi/defi__ez_dex_swaps.sql
models/silver/defi/dex/hashflow/silver_dex__hashflow_v3_pools.sql
models/silver/defi/dex/hashflow/silver_dex__hashflow_v3_pools.yml
models/silver/defi/dex/hashflow/silver_dex__hashflow_v3_swaps.sql
models/silver/defi/dex/hashflow/silver_dex__hashflow_v3_swaps.yml
models/silver/defi/dex/silver_dex__complete_dex_swaps.sql

`dbt run -m models/silver/dex/hashflow/silver_dex__hashflow_v3_pools.sql models/silver/dex/hashflow/silver_dex__hashflow_v3_swaps.sql models/silver/dex/silver_dex__complete_dex_swaps.sql models/gold/defi/defi__ez_dex_swaps.sql --full-refresh`

AN-4087/Add-Hashflow-V3-swaps-and-pools 

---

models/streamline/silver/beacon/_premerge_max_daily_slots.sql
models/streamline/silver/beacon/history/streamline__beacon_validators_history.sql

- adds 653 historical validator calls to pipeline
- includes manual adjustment for skipped slots

validator history model

---

dbt_project.yml
models/beacon_chain/gold/beacon_chain__fact_blocks.sql
models/beacon_chain/gold/beacon_chain__fact_blocks.yml
models/beacon_chain/silver/silver__beacon_blocks.sql
models/beacon_chain/silver/silver__beacon_blocks.yml
models/streamline/silver/beacon/_max_beacon_block_by_date.sql

1. Adds slots with skipped/forked blocks per client request
2. New BOOL column `block_included` and updates incremental strategy to capture reloaded slots if failures occur
3. Requires FR on deployment 
`dbt run -m models/beacon_chain/silver/silver__beacon_blocks.sql  models/beacon_chain/gold/beacon_chain__fact_blocks.sql models/streamline/silver/beacon/_max_beacon_block_by_date.sql --full-refresh`

AN-4223/missing-slots-col

---

models/gold/defi/defi__dim_dex_liquidity_pools.sql
models/silver/defi/dex/silver_dex__complete_dex_liquidity_pools.sql

`dbt run -m models/silver/defi/dex/silver_dex__complete_dex_liquidity_pools.sql models/gold/defi/defi__dim_dex_liquidity_pools.sql --full-refresh`

update lps key

---

models/beacon_chain/gold/beacon_chain__ez_deposits.sql
models/beacon_chain/gold/beacon_chain__ez_withdrawals.sql
models/beacon_chain/gold/beacon_chain__fact_withdrawals.sql

`dbt run -m models/beacon_chain/gold`

withdrawals id

---

models/gold/core/core__fact_blocks.sql
models/gold/core/core__fact_blocks.yml

`dbt run -m models/gold/core/core__fact_blocks.sql`

withdrawals

---

packages.yml

`dbt run -m models/github_actions`

package upgrade

---

models/silver/nft/sales/silver_nft__cryptopunk_sales.yml

Change cryptopunk sales recency test to 7 days

cryptopunks recency to 7 days

---

models/silver/abis/traces/silver__complete_function_abis.sql
models/silver/abis/traces/silver__flat_function_abis.sql

- adds logic to function ABIs model to handle missing names

An 4164/fill function names

---

models/beacon_chain/gold/beacon_chain__fact_blocks.sql

`dbt run -m models/beacon_chain/gold/beacon_chain__fact_blocks.sql`

infer timestamps

---

models/silver/abis/traces/silver__flat_function_abis.sql

`dbt run -m models/silver/abis/traces --full-refresh`

Fix flat function abis

---

models/gold/nft/nft__ez_nft_sales.yml
models/silver/nft/sales/silver_nft__complete_nft_sales.sql
models/silver/nft/sales/silver_nft__magiceden_sales.sql
models/silver/nft/sales/silver_nft__magiceden_sales.yml

`dbt run -m models/silver/nft/sales/silver_nft__magiceden_sales.sql --full-refresh && dbt run -m models/silver/nft/sales/silver_nft__complete_nft_sales.sql --vars '{"HEAL_CURATED_MODEL":["magiceden"]}'`

Add Magic Eden marketplace for ETH

---

models/silver/nft/sales/silver_nft__aggregator_list.sql
models/silver/nft/sales/silver_nft__complete_nft_sales.sql

`dbt run -m models/silver/nft/sales/silver_nft__aggregator_list.sql && dbt run -m models/silver/nft/sales/silver_nft__complete_nft_sales.sql --vars '{"HEAL_MODEL":True}'`

add magic eden tag

---

models/beacon_chain/bronze/bronze__blob_sidecars.sql
models/beacon_chain/bronze/bronze__sepolia_slots.sql
models/beacon_chain/silver/silver__beacon_blocks.sql
models/silver/core/silver__blocks.sql
models/silver/core/silver__receipts.sql
models/silver/core/silver__transactions.sql

- begins pulling blob data from sepolia for testing
- adds new models to core table, will be null until upgrade

An 4613/dencun upgrade

---

models/silver/core/silver__transactions.sql

remove nulls

---

models/beacon_chain/bronze/bronze__blob_sidecars.sql
models/beacon_chain/bronze/bronze__sepolia_slots.sql

move workflows

---

models/beacon_chain/bronze/bronze__blob_sidecars.sql

400 batches at 2 slots per batch is 800, which is more than 2 hours worth of data

error handling

---

models/silver/nft/sales/silver_nft__blur_blend_sales.sql
models/silver/nft/sales/silver_nft__blur_v2.sql
models/silver/nft/sales/silver_nft__complete_nft_sales.sql
models/silver/nft/sales/silver_nft__looksrare_v2.sql
models/silver/nft/sales/silver_nft__seaport_1_5_sales.sql
models/silver/nft/sales/silver_nft__x2y2_decoded_sales.sql

`dbt run -m models/silver/nft/sales/silver_nft__blur_blend_sales.sql models/silver/nft/sales/silver_nft__blur_v2.sql models/silver/nft/sales/silver_nft__looksrare_v2.sql models/silver/nft/sales/silver_nft__seaport_1_5_sales.sql models/silver/nft/sales/silver_nft__x2y2_decoded_sales.sql models/silver/nft/sales/silver_nft__complete_nft_sales.sql`

100 hours lookback

---

models/doc_descriptions/nft/nft_platform_fee.md
models/doc_descriptions/nft/nft_platform_fee_usd.md
models/doc_descriptions/nft/nft_price.md
models/doc_descriptions/nft/nft_price_usd.md
models/silver/nft/sales/silver_nft__magiceden_sales.sql

dbt run -m models/silver/nft/sales/silver_nft__magiceden_sales.sql --full-refresh --vars '{"HEAL_CURATED_MODEL":["magiceden"]}'

add extra fee logic for magic eden

---

models/bronze/api_udf/nft/bronze_api__nft_metadata_list_backdoor.sql

add moonbirds through backdoor 
- run nft list and reads job

add moonbirds

---

macros/tests/missing_decoding.sql
models/silver/core/tests/decoded_logs/test_silver__decoded_logs_recent.yml
models/silver/core/tests/decoded_traces/test_silver__decoded_traces_recent.yml

- uses WETH transfers to look for missing decoding

missing decoding

---

macros/tests/missing_nft_logs.sql

1. Blur test -> changed from >0.5 to != 0. There should be equal number of logs to number of sale txs hence the change 
2. Magic eden test -> current logic doesnt look for the 2 forwarders for Magic Eden. Have to join in traces here to ensure we only check for txs that come through via the 2 forwarders
expected ME test to fail in dev but pass in prod since i just FR-ed ME sales data

nft missing logs test fix

---

models/silver/nft/sales/silver_nft__magiceden_sales.sql

Found some edge cases for erc1155 sales when the fill amount request does not tally with the actual filled amount which results to decoded traces not being accurate. So made changes to pull figures from events + trace calls instead of decoded traces. 1 exception to this is sweepCollection function since the individual trace calls is a cumulative amount instead of individual amounts tied to each nft - hence only in this case, we're still using decoded traces 
`dbt run -m models/silver/nft/sales/silver_nft__magiceden_sales.sql --full-refresh && dbt run -m models/silver/nft/sales/silver_nft__complete_nft_sales.sql --vars '{"HEAL_MODELS":["magiceden"]}'`

fix erc1155 magic eden sales 

---

models/silver/protocols/olas/silver_olas__service_registrations.sql

Add heal logic to handle late-arriving multisig addresses in Olas service registrations

AN-4890/olas-heal

---

models/doc_descriptions/balances/diffs_table_doc.md

`dbt run -m models/gold/core/core__ez_balance_deltas.sql`

remove doc

---

models/silver/defi/lending/complete_lending/silver__complete_lending_liquidations.sql
models/silver/defi/lending/morpho/silver__morpho_liquidations.sql
models/silver/defi/lending/morpho/silver__morpho_liquidations.yml

`dbt run -m models/silver/defi/lending/morpho/silver__morpho_liquidations.sql --full-refresh && dbt run --vars '{"HEAL_MODELS":"morpho"}' -m models/silver/defi/lending/morpho/silver__morpho_liquidations.sql+`

AN-5091/base-morpho-lending-bugs

---

models/doc_descriptions/dex/eth_dex_swaps_amount_in_usd.md
models/doc_descriptions/dex/eth_dex_swaps_amount_out_usd.md
models/gold/defi/defi__ez_dex_swaps.sql

1. Accounts for native asset in amount usd filter in ez_dex_swaps 
2. `dbt run -m models/gold/defi/defi__ez_dex_swaps.sql`

AN-5054/native-null-value

---

models/silver/protocols/aave/lending/silver__aave_repayments.sql

`dbt run -m models/silver/protocols/aave/lending/silver__aave_repayments.sql --full-refresh -t dev-2xl && dbt run --vars '{"HEAL_MODELS":"aave"}' -m models/silver/defi/lending/complete_lending/silver__complete_lending_repayments.sql`

aave-repay-bug 

---

models/silver/defi/lending/morpho/silver__morpho_liquidations.sql

`dbt run -m models/silver/defi/lending/morpho/silver__morpho_liquidations.sql --full-refresh && dbt run --vars '{"HEAL_MODELS":"morpho"}' -m models/silver/defi/lending/complete_lending/silver__complete_lending_liquidations.sql`

An 5235/morpho liquidation dupe bug

---

.github/workflows/dbt_run_temp_traces2.yml
models/silver/core/silver__fact_traces2.sql

`dbt run -m models/silver/core/silver__fact_traces2.sql --full-refresh`

reload gold traces

---

dbt_project.yml
models/doc_descriptions/dex/eth_ez_dex_swaps_table_doc.md
models/gold/defi/defi__ez_dex_swaps.sql
models/silver/defi/dex/silver_dex__complete_dex_swaps.sql
models/silver/defi/dex/woofi/silver_dex__woofi_swaps.sql
models/silver/defi/dex/woofi/silver_dex__woofi_swaps.yml

1. Adds woofi to dex swaps
2. Adds persist_docs to dbt_project.yml
`dbt run -m models/silver/defi/dex/woofi/silver_dex__woofi_swaps.sql --full-refresh && dbt run -m models/silver/defi/dex/silver_dex__complete_dex_swaps.sql --vars '{"HEAL_MODELS":"woofi"}'`

AN-5304/woofi-v2

---

models/silver/nft/lending/nftfi_v2/silver_nft__nftfi_v2_liquidations.yml
models/silver/nft/lending/nftfi_v2/silver_nft__nftfi_v2_loans.yml
models/silver/nft/lending/nftfi_v2/silver_nft__nftfi_v2_new_loans.yml
models/silver/nft/lending/nftfi_v2/silver_nft__nftfi_v2_obligation_receipts.yml
models/silver/nft/lending/nftfi_v2/silver_nft__nftfi_v2_repayments.yml

removing v2 recency test since there's a v3

remove nftfiv2 recency test

---

models/silver/defi/liquid_staking/guarded/silver_lsd__guarded_deposits.sql

add function sig to fix duplicate rows 
`dbt run -m models/silver/defi/liquid_staking/guarded/silver_lsd__guarded_deposits.sql --full-refresh  && dbt run -m models/silver/defi/liquid_staking/silver_lsd__complete_lsd_deposits.sql --vars '{"HEAL_MODELS": ["guarded"]}'`

Fix Guarded LST

---

models/beacon_chain/bronze/bronze__blob_sidecars.sql
models/beacon_chain/silver/silver__blob_sidecars.sql
models/sources.yml
models/streamline/bronze/beacon/bronze__streamline_beacon_blobs.sql
models/streamline/bronze/beacon/bronze__streamline_fr_beacon_blobs.sql
models/streamline/bronze/beacon/bronze__streamline_fr_beacon_blobs_v2.sql
models/streamline/silver/beacon/complete/streamline__complete_beacon_blobs.sql
models/streamline/silver/beacon/complete/streamline__complete_beacon_blocks.sql
models/streamline/silver/beacon/realtime/streamline__beacon_blobs_realtime.sql

- `dbt run -m tag:bronze_beacon_blobs models/streamline/silver/beacon/complete/streamline__complete_beacon_blobs.sql models/streamline/silver/beacon/realtime/streamline__beacon_blobs_realtime.sql --full-refresh`

blobs model

---

.github/workflows/dbt_run_traces_fix.yml
models/silver/core/traces2_fix/silver__fact_traces2_fix.sql

`dbt run -m models/silver/core/traces2_fix/silver__fact_traces2_fix.sql --full-refresh`

Fix traces2/ethereum

---

models/silver/defi/lending/fraxlend/silver__fraxlend_asset_details.sql

`dbt run -m models/silver/defi/lending/fraxlend/silver__fraxlend_asset_details.sql models/silver/defi/lending/fraxlend/silver__fraxlend_deposits.sql --full-refresh && dbt run --vars '{"HEAL_MODELS":"fraxlend"}' -m models/silver/defi/lending/complete_lending/silver__complete_lending_deposits.sql`

fix-fraxlend-asset-details 

---

models/silver/nft/silver__nft_mints.sql

dbt run -m models/silver/nft/silver__nft_mints.sql --vars '{"LOOKBACK": "24 hours"}'

revert to logid for nft mints

---

models/silver/defi/lending/aave/silver__aave_token_backfill.sql

`dbt run -m models/silver/defi/lending/aave -t dev-2xl --full-refresh && dbt run --vars '{"HEAL_MODELS":"aave"}' -m models/silver/defi/lending/complete_lending`

aave-token-model-tag-fixe

---

models/gold/l2/l2__ez_state_validation.sql

`dbt run -m models/gold/l2/l2__ez_state_validation.sql --full-refresh`

remove invocation id from state table 

---

models/doc_descriptions/fsc_evm/nft.md
models/gold/defi/defi__ez_dex_swaps.yml
models/gold/defi/defi__ez_liquid_staking_withdrawals.yml
models/gold/defi/lending/defi__ez_lending_liquidations.yml
models/gold/nft/lending/nft__ez_lending_repayments.yml
models/gold/nft/nft__ez_nft_sales.yml
models/gold/nft/nft__ez_nft_transfers.yml

Columns with missing descriptions:
- nft__ez_nft_transfers -> token_transfer_type, is_mint
- nft__ez_nft_sales -> tx_fee, tx_fee_usd
- defi__ez_dex_swaps -> origin_to_address, pool_name
- defi__ez_liquid_staking_withdrawals -> ez_liquid_staking_withdrawals_id
- defi__ez_lending_liquidations_id -> ez_lending_liquidations_id
- nft__ez_lending_repayments -> loan_paid_timestamp

AN-5941/fix missing column descriptions

---

models/silver/defi/lending/compound/silver__comp_asset_details.sql
models/silver/defi/lending/compound/silver__comp_borrows.sql
models/silver/defi/lending/compound/silver__comp_deposits.sql
models/silver/defi/lending/compound/silver__comp_liquidations.sql
models/silver/defi/lending/compound/silver__comp_redemptions.sql
models/silver/defi/lending/compound/silver__comp_repayments.sql

`dbt run -m models/silver/defi/lending/compound --full-refresh && dbt run -m models/silver/defi/lending/complete_lending --vars '{"HEAL_MODELS":"comp"}' `

AN-5324/add-support-for-dynamic-compv3-token-adds

---

models/bronze/nft/bronze_api__nft_metadata_list_filter.sql
models/bronze/nft/bronze_api__nft_metadata_list_request.sql
models/bronze/nft/original_500_collection/bronze_api__nft_metadata_list.sql
models/silver/nft/lending/arcade_v1/silver_nft__arcade_v1_loans.sql
models/silver/nft/lending/nftfi_v2/silver_nft__nftfi_v2_new_loans.sql
models/silver/nft/lending/nftfi_v2/silver_nft__nftfi_v2_repayments.sql
models/silver/nft/mev/arbitrage/silver_nft__arbitrage_raw.sql
models/silver/nft/sales/artblocks/silver_nft__artblocks_base_sales.sql
models/silver/nft/sales/silver_nft__blur_decoded_sales.sql
models/silver/nft/sales/silver_nft__blur_v2.sql
models/silver/nft/sales/silver_nft__cryptopunk_sales.sql
models/silver/nft/sales/silver_nft__looksrare_decoded_sales.sql
models/silver/nft/sales/silver_nft__looksrare_v2.sql
models/silver/nft/sales/silver_nft__nftx_decoded_sales.sql
models/silver/nft/sales/silver_nft__rarible_decoded_sales.sql
models/silver/nft/sales/silver_nft__rarible_v2_sales.sql
models/silver/nft/sales/silver_nft__wyvern_decoded_sales.sql
models/silver/nft/sales/silver_nft__x2y2_decoded_sales.sql
models/silver/nft/sales/sudoswap/silver_nft__sudoswap_v1_sales.sql

clean up references to silver nft transfers and nft mints

Nft transfers switch

---

models/silver/defi/lending/morpho/silver__morpho_liquidations.sql
models/silver/defi/lending/morpho/silver__morpho_liquidations.yml

`dbt run -m models/silver/defi/lending/morpho/silver__morpho_liquidations.sql --full-refresh`

morpho-liquidation-fix

---

.github/workflows/dbt_run_scheduled_curated.yml

- will remove in a week after backfill reads is done

add everclear backfill run to curated workflow

---

macros/streamline/bronze/streamline_external_table_query_v0.sql
models/streamline/bronze/beacon/bronze__streamline_beacon_blocks.sql
models/streamline/bronze/beacon/bronze__streamline_fr_beacon_blocks_v1.sql
models/streamline/bronze/beacon/bronze__streamline_fr_beacon_blocks_v2.sql

```
dbt run -m models/streamline/bronze/beacon/bronze__streamline_beacon_blocks.sql models/streamline/bronze/beacon/bronze__streamline_fr_beacon_blocks_v1.sql models/streamline/bronze/beacon/bronze__streamline_fr_beacon_blocks_v2.sql models/streamline/bronze/beacon/bronze__streamline_fr_beacon_blocks.sql --full-refresh && dbt run -m models/streamline/silver/beacon/complete/streamline__complete_beacon_blocks.sql

data not null
