- models/silver/traces/silver__traces.sql
- see tx `0x0e51c8b1312161aa825c7693e4cd36335b671a3b5acfa8f70240cad2b01b3766` for bug (two ingested at dates)
- if we replay a block into chainwalkers and the prior version has an incorrect record, the incorrect record stays in the table even if we delete and replay the block 
- i will have to delete and replay ~350k blocks into traces
> fix traces

- macros/sp_create_prod_clone.sql
Clone fails due to existing future table ownership grants.
- update SP to handle this for bronze schema
> AN-1821 Fix Clone Failure 

- models/silver/streamline/streamline__complete_eth_balances.sql
- models/silver/streamline/streamline__complete_token_balances.sql
- optimize models to avoid table scans using partition pruning
- use registered_on instead of last_modified for incremental logic
> Streamline Completed Balances Optimizations

- models/gold/core__ez_eth_transfers.yml
- models/silver/silver__blocks.yml
- models/silver/silver__transactions.yml
- tests/ethereum/test_silver__transactions_tx_gaps.sql
turns on:
- block gap test
- tx gap test
- blocks txs vs. transaction count test 
tweaks:
- gives `ez_eth_transfers` a day to get the usd price
> turn back on tests

- models/silver/nft/silver_nft__seaport_sales.sql
- excludes gem contract when looking for payments to sellers, OS, or royalties
> exclude gem

- models/silver/silver__nft_transfers.sql
fix NFT_transfer table to pull the correct tokenId and have no null values in the to_address column.  Some to_address still indicate the burn address instead of the wallet address because that's how they are in the silver.logs table, and the data is pulled from there.
> An 1961 fix ethereum nft bug

- models/silver/dex/silver_dex__synthetix_swaps.sql
- models/silver/dex/silver_dex__synthetix_swaps.yml
add synthetix swaps silver table following the specifications given by Flipside in [this doc](https://docs.google.com/document/d/1kPUehVFgqsiepXbqddXINw_P2Mf4JIFyQ7yQZODQ-qs/edit#)
the logs for the tests covering recency, nulls, duplicates and data type checks can be found below
[test_logs_synthetixs_table.log](https://github.com/FlipsideCrypto/ethereum-models/files/9531812/test_logs_synthetixs_table.log)
> add synthetix swaps silver table

- models/uniswapv3/silver/silver__univ3_swaps.sql
> exclude non v3 pools

- models/uniswapv3/silver/silver__univ3_lp_actions.sql
- models/uniswapv3/silver/silver__univ3_position_collected_fees.sql
1. Modified `liquidity_provider` and `nf_position_manager_address` columns based on corrected logic so that models have column parity with eachother
2. Associated downstream uniswap v3 models will require a full refresh (silver + core lp_actions, position_collected_fees, positions)
3. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2516)
> An 2516/lp-actions-col-adj

- models/gold/core__ez_eth_transfers.sql
1. Changed source from `token_prices_hourly` to ref `token_prices_all_providers_hourly` (new prices model)
2. `core__ez_eth_transfers` requires FR
> AN-2659/missing-weth-prices

- models/silver/silver__token_meta_reads.sql
1. Added regex to heal CTE filtering to include blank `token_name` (rather than just NULL)
2. Fixes bug on `ez_current_balances` w/incorrect decimals
3. `silver.contracts` requires FR after `silver.token_meta_reads` incremental
4. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2753)
> AN-2753/incorrect-decimals

- models/silver/dex/silver_dex__curve_pools.sql
- models/silver/dex/silver_dex__curve_swaps.sql
1. Rebuilt `curve_pools` and `curve_swaps` to fill NULL `token_addresses` accurately
2. Requires FR of `silver_dex.curve_pools`+ 
3. Clears up curve related test failures
> AN-2810/curve-rebuild

- models/silver/streamline/streamline__complete_token_balances.sql
- models/silver/streamline/streamline__token_balances_history.sql
- models/silver/streamline/streamline__token_balances_realtime.sql
- includes reverted executions as complete
- expands history process to 16m range
- last three days only on balances
> balances tweaks

- models/silver/balances/silver__eth_balance_diffs.sql
- models/silver/balances/silver__token_balance_diffs.sql
- removes qualify to include all records for an address in the order by for last balance, and then filters the old records out via and inner join on the min record for that user/token so that we don't load a ton of rows every time
> incremental fix

- models/Sushi/sushi__dim_distributor_reward_schedule.sql
- models/Sushi/sushi__dim_distributor_reward_schedule.yml
- models/Sushi/sushi__ez_borrowing.sql
- models/Sushi/sushi__ez_lending.sql
- models/Sushi/sushi__ez_swaps.sql
- models/Sushi/sushi__ez_swaps.yml
- models/gold/core__ez_eth_transfers.sql
- models/gold/core__fact_hourly_token_prices.sql
- models/gold/core__fact_hourly_token_prices.yml
- models/silver/nft/silver_nft__blur_decoded_sales.sql
- models/silver/nft/silver_nft__cryptopunk_sales.sql
- models/silver/nft/silver_nft__looksrare_decoded_sales.sql
- models/silver/nft/silver_nft__nftx_decoded_sales.sql
- models/silver/nft/silver_nft__seaport_1_4_sales.sql
- models/silver/nft/silver_nft__seaport_decoded_sales.sql
- models/silver/nft/silver_nft__sudoswap_sales.sql
- models/silver/nft/silver_nft__x2y2_decoded_sales.sql
- models/silver/prices/silver__token_prices_all_providers_hourly.sql
- models/silver/prices/silver__token_prices_all_providers_hourly.yml
- models/silver/prices/silver__token_prices_coin_gecko_hourly.sql
- models/silver/prices/silver__token_prices_coin_gecko_hourly.yml
- models/silver/prices/silver__token_prices_coin_market_cap_hourly.sql
- models/silver/prices/silver__token_prices_coin_market_cap_hourly.yml
- models/sources.yml
1. Changed source for `core.fact_hourly_token_prices` to `crosschain.ez_hourly_prices`
2. Replaced any references to `silver` prices with the `core` view and disabled it
3. Disabled sushi models as part of deprecation process
> AN-2448/eth-price-pivot

- models/silver/streamline/streamline__eth_balances.sql
- models/silver/streamline/streamline__eth_balances_history.sql
- models/silver/streamline/streamline__token_balances_history.sql
- expands balances history models to the 17m range 
- excludes failed eth transfers
> balances updates

- models/silver/silver__nft_transfers.sql
- models/silver/silver__nft_transfers.yml
Adding ERC1155's TransferBatch logic in nft transfers table 
- each event can contain transfers of multiple tokenIds + a quantity value 
- since multiple tokenIds can appear in the same event (and the same tokenId can appear twice in the same event too), I'm introducing a new token_log_id column to qualify
> transferbatch logic

- models/bronze/api_udf/snapshot/bronze_api__snapshot_votes.sql
- models/silver/silver__snapshot.yml
1. increased limit on # of records per run
2. moved recency test to _inserted_timestamp
> AN-3336/snapshot-vote-cadence

- models/silver/nft/silver_nft__complete_nft_sales.sql
Removed null tokenid duplicates in the silver__nft_labels_temp table that causes duplicates in the complete nft sales table
> remove null tokenid

- models/silver/abis/silver__complete_event_abis2.sql
- models/silver/abis/silver__proxies2.sql
- adds logic to `complete_function_abis` to handle null inputs, e.g. `decimals()`
- builds a new version of `complete_event_abis(2)` and `proxies(2)` to test incremental loads with the goal of consolidating all abi jobs into the non-real time workflows
> incremental abis

- models/gold/nft/core__ez_nft_transfers.sql
- models/silver/nft/silver__nft_transfers.sql
- models/silver/nft/silver_nft__complete_nft_sales.sql
- models/silver/nft/silver_nft__seaport_1_1_sales.sql
1. Cast erc1155 as string in nft transfers 
2. Improving complete nft sale incremental run times 
3. Added blurEth manual decimals adjustment in complete nft sales 
4. Removed ref to silver nft transfers in seaport 1.1
> erc1155 fix 

- models/gold/protocols/uniswapv3/uniswapv3__ez_lp_actions.sql
- models/gold/protocols/uniswapv3/uniswapv3__ez_lp_actions.yml
- models/gold/protocols/uniswapv3/uniswapv3__ez_pool_stats.sql
- models/gold/protocols/uniswapv3/uniswapv3__ez_pool_stats.yml
- models/gold/protocols/uniswapv3/uniswapv3__ez_pools.sql
- models/gold/protocols/uniswapv3/uniswapv3__ez_pools.yml
- models/gold/protocols/uniswapv3/uniswapv3__ez_position_collected_fees.sql
- models/gold/protocols/uniswapv3/uniswapv3__ez_positions.sql
- models/gold/protocols/uniswapv3/uniswapv3__ez_positions.yml
- models/gold/protocols/uniswapv3/uniswapv3__ez_swaps.sql
- models/silver/protocols/uniswapv3/silver__univ3_lp_actions.sql
- models/silver/protocols/uniswapv3/silver__univ3_lp_actions.yml
- models/silver/protocols/uniswapv3/silver__univ3_pool_stats.sql
- models/silver/protocols/uniswapv3/silver__univ3_pool_stats.yml
- models/silver/protocols/uniswapv3/silver__univ3_pools.sql
- models/silver/protocols/uniswapv3/silver__univ3_pools.yml
- models/silver/protocols/uniswapv3/silver__univ3_position_collected_fees.sql
- models/silver/protocols/uniswapv3/silver__univ3_positions.sql
- models/silver/protocols/uniswapv3/silver__univ3_positions.yml
- models/silver/protocols/uniswapv3/silver__univ3_swaps.sql
- Moved gold view price joins and transformations into silver incremental tables
- Will require a FR on silver and gold level uni v3 models:
- `dbt run -m models/silver/protocols/uniswapv3 models/gold/protocols/uniswapv3 --full-refresh -t dev-2xl`
- `ez_pool_stats` > 300M rows so will run with DBT emergency
- Silver table updates are backward compatible with downstream streamline read models so won't need to FR there
- All models successful with `dbt run -m models/silver/protocols/uniswapv3+` except `ethereum_share` models--But I am seeing the same issues on main branch so it does not have to do with this PR specifically
- Query time for Univ3 is cut down by ~85-95%
> AN-3995/optimize-univ3-views

- models/beacon_chain/gold/beacon_chain__fact_attestations.sql
- models/beacon_chain/gold/beacon_chain__fact_attestations.yml
- models/beacon_chain/silver/silver__beacon_attestations.sql
- models/beacon_chain/silver/silver__beacon_attestations.yml
- models/beacon_chain/silver/silver__beacon_blocks.sql
- models/beacon_chain/silver/silver__beacon_blocks.yml
- models/beacon_chain/silver/silver__beacon_deposits.sql
- models/beacon_chain/silver/silver__beacon_withdrawals.sql
- models/streamline/bronze/beacon/bronze__beacon_blocks.sql
- models/streamline/bronze/beacon/bronze__beacon_validators.sql
- models/streamline/bronze/beacon/bronze__fr_beacon_blocks.sql
- models/streamline/bronze/beacon/bronze__fr_beacon_validators.sql
1. Added calc for `epoch_number` and modified downstream models accordingly to properly capture BC activity and missing withdrawal index
2. Added `attestation_slot` column
3. Modified where clause in bronze to properly filter values
4. Requires FR on beacon models for updated epoch values and new column
5. Requires FR on complete models + history/realtime jobs to reload failed blocks (confirmed accurate in node)
> AN-4156/missing-index

- models/silver/defi/liquid_staking/silver_lsd__complete_lsd_deposits.sql
- models/silver/defi/liquid_staking/silver_lsd__complete_lsd_withdrawals.sql
- models/silver/defi/liquid_staking/stakewise/silver_lsd__stakewise_v3_deposits.sql
- models/silver/defi/liquid_staking/stakewise/silver_lsd__stakewise_v3_deposits.yml
- models/silver/defi/liquid_staking/stakewise/silver_lsd__stakewise_v3_vaults.sql
- models/silver/defi/liquid_staking/stakewise/silver_lsd__stakewise_v3_vaults.yml
- models/silver/defi/liquid_staking/stakewise/silver_lsd__stakewise_v3_withdrawals.sql
- models/silver/defi/liquid_staking/stakewise/silver_lsd__stakewise_v3_withdrawals.yml
1. Adds new silver tables for stakewise-v3, including vaults, deposits and withdrawals
Requires `dbt run -m models/silver/defi/liquid_staking/stakewise+ --full-refresh --exclude models/silver/defi/liquid_staking/stakewise/silver_lsd__stakewise_deposits.sql`
> AN-4282/stakewise-v3-lsd

- models/silver/defi/dex/curve/silver_dex__curve_pools.sql
1. New deployer contract to pull in new pools, including 28 with crvUSD as requested by user
2. Includes temp logic to incrementally read new pools only (requires follow up PR to revert this logic)
```dbt run -m models/silver/defi/dex/curve/silver_dex__curve_pools.sql && dbt run -m models/silver/defi/dex/curve/silver_dex__curve_swaps.sql models/silver/defi/dex/silver_dex__complete_dex_liquidity_pools.sql models/silver/defi/dex/silver_dex__complete_dex_swaps.sql --full-refresh```
> AN-3883/new-crv-pools

- models/doc_descriptions/bridge/evm_bridge_activity.md
- models/gold/defi/defi__ez_bridge_activity.sql
- models/silver/defi/bridge/dln/silver_bridge__dln_debridge_createdorder.sql
- models/silver/defi/bridge/dln/silver_bridge__dln_debridge_createdorder.yml
- models/silver/defi/bridge/eywa/silver_bridge__eywa_requestsent.sql
- models/silver/defi/bridge/eywa/silver_bridge__eywa_requestsent.yml
- models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql
1. Adds two new bridge protocols
`dbt run -m models/silver/defi/bridge/dln/silver_bridge__dln_debridge_createdorder.sql models/silver/defi/bridge/eywa/silver_bridge__eywa_requestsent.sql --full-refresh && dbt run -m models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql+ --var '{"HEAL_CURATED_MODEL":["dln_debridge","eywa"]}'`
> AN-4451/more-bridge-protocols

- .github/workflows/dbt_run_streamline_traces_decoder_history_range_test.yml
- macros/streamline/models.sql
- models/streamline/silver/decoder/history/traces/range_test/streamline__decode_traces_history_018908895_018943246.sql
- models/streamline/silver/decoder/history/traces/range_test/streamline__decode_traces_history_018943247_018981366.sql
- models/streamline/silver/decoder/history/traces/range_test/streamline__decode_traces_history_018981367_019017880.sql
- models/streamline/silver/decoder/history/traces/range_test/streamline__decode_traces_history_019017881_019050916.sql
- models/streamline/silver/decoder/history/traces/range_test/streamline__decode_traces_history_019050917_019083530.sql
- models/streamline/silver/decoder/history/traces/range_test/streamline__decode_traces_history_019083531_019116985.sql
- models/streamline/silver/decoder/history/traces/range_test/streamline__decode_traces_history_019116986_019148786.sql
- models/streamline/silver/decoder/history/traces/range_test/streamline__decode_traces_history_019148787_019182777.sql
- models/streamline/silver/decoder/history/traces/range_test/streamline__decode_traces_history_019182778_019220379.sql
- models/streamline/silver/decoder/history/traces/range_test/streamline__decode_traces_history_019220380_019255380.sql
- models/streamline/silver/decoder/history/traces/range_test/streamline__decode_traces_history_019255381_019290381.sql
- models/streamline/silver/decoder/history/traces/range_test/streamline__decode_traces_history_019290382_019325382.sql
- models/streamline/silver/decoder/history/traces/range_test/streamline__decode_traces_history_019325383_019360383.sql
- traces history models from Jan 1 2024 onwards
- `dbt run -m models/streamline/silver/decoder/history/traces/range_test --full-refresh`
> traces history

- models/silver/optimism/silver__optimism_bedrock_state_hashes.sql
Full refreshed dev with new model and compared to prod. New model matches exactly to old:
```
select
*
from 
ethereum_dev.silver.optimism_bedrock_state_hashes D
INNER JOIN 
ethereum.silver.optimism_bedrock_state_hashes P
ON
D.STATE_TX_HASH = P.STATE_TX_HASH
WHERE
(D.state_tx_hash <> P.state_tx_hash)
or
(D.state_block_number <> P.state_block_number)
or
(D.state_block_timestamp <> P.state_block_timestamp)
or
(D.state_batch_index <> P.state_batch_index)
or
(D.state_batch_root <> P.state_batch_root)
or
(D.state_batch_size <> P.state_batch_size)
or
(D.state_prev_total_elements <> P.state_prev_total_elements)
or
(D.state_min_block <> P.state_min_block)
or
(D.state_max_block <> P.state_max_block)
```
> op-bedrock-decoded-logs-to-logs-fix

- models/silver/nft/lending/blur/silver_nft__blend_new_loans.sql
- models/silver/nft/lending/blur/silver_nft__blend_new_loans.yml
Change logic to ensure only new loan transactions go through - for cases when a refinance transaction lands in the table earlier than a new loan transaction 
`dbt run -m models/silver/nft/lending/blur/silver_nft__blend_new_loans.sql models/silver/nft/lending/blur/silver_nft__blend_loans.sql models/silver/nft/lending/blur/silver_nft__blend_repayments.sql --full-refresh && dbt run -m models/silver/nft/lending/complete_lending/silver_nft__complete_loans.sql --vars '{"HEAL_CURATED_MODEL":["blend"]}' && dbt run -m models/silver/nft/lending/complete_lending/silver_nft__complete_repayments.sql --var '{"HEAL_CURATED_MODEL":["blend"]}'`
> Fix blend new loans logic 

- models/bronze/api_udf/nft/bronze_api__nft_metadata_reads_new.sql
`dbt run -m models/bronze/api_udf/nft/bronze_api__nft_metadata_reads_new.sql && dbt run -m models/bronze/api_udf/nft/bronze_api__nft_metadata_reads_new.sql models/silver/nft/silver__nft_collection_metadata.sql`
- next PR to remove nft address specification and change to the right json_request column
> Add backdoor logic to omit metadata fields

- models/doc_descriptions/nft/nft_event_type.md
- models/gold/nft/nft__ez_nft_sales.yml
- models/silver/nft/lending/complete_lending/silver_nft__complete_liquidations.sql
- models/silver/nft/lending/complete_lending/silver_nft__complete_loans.sql
- models/silver/nft/lending/complete_lending/silver_nft__complete_repayments.sql
- models/silver/nft/sales/artblocks/silver_nft__artblocks_base_sales.sql
- models/silver/nft/sales/artblocks/silver_nft__artblocks_base_sales.yml
- models/silver/nft/sales/artblocks/silver_nft__artblocks_sales.sql
- models/silver/nft/sales/artblocks/silver_nft__artblocks_sales.yml
- models/silver/nft/sales/artblocks/silver_nft__artblocks_seller_reads.sql
- models/silver/nft/sales/artblocks/silver_nft__artblocks_seller_reads.yml
- models/silver/nft/sales/silver_nft__complete_nft_sales.sql
1. Add artblocks model 
- a base model to get a list of new artblock sales 
- a reads model to get artist addresses for new project ids 
- a final sales model 
2. Add a logic in complete nft sales to join in decimals and symbol using the contracts model as a backup where there are no entries in the price table 
3. Add a new event type called "mint" only for Art blocks. Existing event types are sale, bid_won and redeem. 
4. update unique key in complete models so that vars runs doesn't delete rows
`dbt run -m models/silver/nft/sales/artblocks --full-refresh && dbt run -m models/silver/nft/sales/silver_nft__complete_nft_sales.sql --vars '{"HEAL_CURATED_MODEL":["artblocks"]}'`
> add art blocks, add decimals logic in complete nft

- models/silver/nft/sales/silver_nft__magiceden_sales.sql
included edge case where royalty trace called was reverted but royalty was still paid 
`dbt run -m models/silver/nft/sales/silver_nft__magiceden_sales.sql --full-refresh && dbt run -m models/silver/nft/sales/silver_nft__complete_nft_sales.sql --vars '{"HEAL_CURATED_MODEL":["magiceden"]}'`
> Fix magic eden royalty bug 

- models/silver/nft/sales/silver_nft__aggregator_list.sql
- models/silver/nft/sales/silver_nft__complete_nft_sales.sql
Added a way to add in aggregators without a full refresh 
1. New aggregator list model for 2 types of aggregators, can update new aggregators here 
- calldata -> these are added as aggregator_name entries
- routers -> these replaces existing platform_name entries
2. In complete nft sales model, use existing labels heal logic to add logic to heal for aggregator names as well 
- also dropped the platform_name unique key as platform names can be changed upon a heal incremental run 
`dbt run -m models/silver/nft/sales/silver_nft__aggregator_list.sql --full-refresh && dbt run -m models/silver/nft/sales/silver_nft__complete_nft_sales.sql --vars '{"HEAL_MODEL":True}'`
> Add aggregator heal logic 

- macros/tests/missing_nft_logs.sql
- models/silver/nft/sales/silver_nft__complete_nft_sales.sql
- models/silver/nft/sales/silver_nft__complete_nft_sales.yml
- models/silver/nft/sales/silver_nft__seaport_1_6_sales.sql
- models/silver/nft/sales/silver_nft__seaport_1_6_sales.yml
1. Add seaport 1.6
2. turn off recency for seaport 1.5
3. change missing logs test to seaport 1.6
dbt run -m models/silver/nft/sales/silver_nft__seaport_1_6_sales.sql --full-refresh && dbt run -m models/silver/nft/sales/silver_nft__complete_nft_sales.sql --vars '{"HEAL_CURATED_MODEL":["seaport_1_6"]}'
> Add seaport 1.6

- models/silver/nft/sales/silver_nft__magiceden_sales.sql
grabs erc1155 value from events instead of traces
- just discovered cases where traces doesnt represent right amount of erc1155 value 
`dbt run -m models/silver/nft/sales/silver_nft__magiceden_sales.sql --full-refresh && dbt run -m models/silver/nft/sales/silver_nft__complete_nft_sales.sql --vars '{"HEAL_MODELS":["magiceden"]}'`
> magic eden 1155 value fix 

- models/silver/nft/lending/nftfi_v2/silver_nft__nftfi_v2_liquidations.yml
increase recency for nftfi v2 liquidations because there's a new refinancing model that is causing liquidations to not join correctly
> increase recency for nftfi v2 liquidations 

- models/silver/nft/sales/silver_nft__magiceden_sales.sql
- missing txs due to eth 2.0 migration
`dbt run -m models/silver/nft/sales/silver_nft__magiceden_sales.sql && dbt run -m models/silver/nft/sales/silver_nft__complete_nft_sales.sql --vars '{"LOOKBACK":"72 hours"}'`
> reload 72 hours of ME 

- models/beacon_chain/silver/silver__beacon_validators.sql
- models/streamline/bronze/beacon/bronze__streamline_beacon_validators.sql
- models/streamline/silver/beacon/complete/streamline__complete_beacon_validators.sql
- models/streamline/silver/beacon/history/streamline__beacon_blocks_history.sql
- models/streamline/silver/beacon/history/streamline__beacon_validators_history.sql
- models/streamline/silver/beacon/realtime/streamline__beacon_blocks_realtime.sql
- models/streamline/silver/beacon/realtime/streamline__beacon_validators_realtime.sql
1. Reinstates SL 2.0 for Beacon Validators - initially reverted in PRs [951](https://github.com/FlipsideCrypto/ethereum-models/pull/951) and [952](https://github.com/FlipsideCrypto/ethereum-models/pull/952)
3. Updates config params
4. Requires SL multi-processing in prod and `dbt run -m models/streamline/bronze/beacon/bronze__streamline_beacon_validators.sql --full-refresh`
> beacon-validators-sl2

- models/silver/defi/lending/compound/silver__comp_market_stats.sql
we've already removed the gold table, and no other models rely on this. Will be dropping this table after offsite
> add stale to compound market stats

- macros/decoder/decoded_traces_history.sql
- models/streamline/silver/decoder/realtime/streamline__decode_traces_realtime.sql
modify child of logic so that last number in trace address which are not single digits gets joined in correctly with parents. Super low impact so no traces reloading is necessary 
child -> parent mapping 
trace origin -> origi 
trace 0 -> origin 
trace 0_10 -> 0
> modify child logic for decoded traces

- data/silver_bridge__native_bridges_seed.csv
- data/silver_bridge__standard_dst_chain_seed.csv
- models/silver/defi/bridge/axie/silver_bridge__axie_infinity_depositrequested.sql
- models/silver/defi/bridge/axie/silver_bridge__axie_infinity_depositrequested.yml
- models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql
Splits axie into own bridge model via logs
Requires delete from seed, silver and crosschain
1. Run delete statements to remove axie bridge v2 from native tables and avoid double counting: `ethereum.silver_bridge.native_bridges_seed`, `ethereum.silver_bridge.native_bridges_transfers_out`, `ethereum.silver_bridge.complete_bridge_activity`, `crosschain.silver.complete_bridge_activity`
2. `dbt seed -m silver_bridge__standard_dst_chain_seed && dbt run -m models/silver/defi/bridge/axie/silver_bridge__axie_infinity_depositrequested.sql --full-refresh && dbt run -m models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql models/gold/defi/defi__ez_bridge_activity.sql --vars '{"HEAL_MODELS":"axie_infinity_v2"}'`
> AN-5770/ronin-bridge-addr

- models/silver/defi/bridge/across/silver_bridge__across_v3fundsdeposited.sql
- added new topic for new across implementation contract
- changed to `fact_event_logs` for correct decoding of addresses for new contract
1. `dbt run -m models/silver/defi/bridge/across/silver_bridge__across_v3fundsdeposited.sql --full-refresh && dbt run -m models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql --vars '{"HEAL_MODELS":"across_v3"}'`
> topics updates

- models/silver/nft/lending/blur/silver_nft__blend_loans.sql
- issue is in decoded event log, a single block can have multiple txs with different inserted timestamps and because UK is block number, it's possible that txs are not replaced when block number is deleted and inserted 
- this change ensures we load in all events by block number instead of just inserted timestamp
> incremental change for blend loans
